//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Services.Testing.FolderService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputFormat", Namespace="http://schemas.datacontract.org/2004/07/GIS.Services")]
    public enum OutputFormat : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        html = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        json = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        pjson = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FolderService.IFolderService")]
    public interface IFolderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolderService/Get", ReplyAction="http://tempuri.org/IFolderService/GetResponse")]
        string Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolderService/Get", ReplyAction="http://tempuri.org/IFolderService/GetResponse")]
        System.Threading.Tasks.Task<string> GetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolderService/GetDescription", ReplyAction="http://tempuri.org/IFolderService/GetDescriptionResponse")]
        string GetDescription(GIS.Services.Testing.FolderService.OutputFormat format);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolderService/GetDescription", ReplyAction="http://tempuri.org/IFolderService/GetDescriptionResponse")]
        System.Threading.Tasks.Task<string> GetDescriptionAsync(GIS.Services.Testing.FolderService.OutputFormat format);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFolderServiceChannel : GIS.Services.Testing.FolderService.IFolderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FolderServiceClient : System.ServiceModel.ClientBase<GIS.Services.Testing.FolderService.IFolderService>, GIS.Services.Testing.FolderService.IFolderService {
        
        public FolderServiceClient() {
        }
        
        public FolderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FolderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FolderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FolderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Get() {
            return base.Channel.Get();
        }
        
        public System.Threading.Tasks.Task<string> GetAsync() {
            return base.Channel.GetAsync();
        }
        
        public string GetDescription(GIS.Services.Testing.FolderService.OutputFormat format) {
            return base.Channel.GetDescription(format);
        }
        
        public System.Threading.Tasks.Task<string> GetDescriptionAsync(GIS.Services.Testing.FolderService.OutputFormat format) {
            return base.Channel.GetDescriptionAsync(format);
        }
    }
}
