//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Services.Testing.FolderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FolderService.IFolderService")]
    public interface IFolderService {
        
        // CODEGEN: Generating message contract since element name format from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolderService/GetDescription", ReplyAction="http://tempuri.org/IFolderService/GetDescriptionResponse")]
        GIS.Services.Testing.FolderService.GetDescriptionResponse GetDescription(GIS.Services.Testing.FolderService.GetDescriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolderService/GetDescription", ReplyAction="http://tempuri.org/IFolderService/GetDescriptionResponse")]
        System.Threading.Tasks.Task<GIS.Services.Testing.FolderService.GetDescriptionResponse> GetDescriptionAsync(GIS.Services.Testing.FolderService.GetDescriptionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDescriptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDescription", Namespace="http://tempuri.org/", Order=0)]
        public GIS.Services.Testing.FolderService.GetDescriptionRequestBody Body;
        
        public GetDescriptionRequest() {
        }
        
        public GetDescriptionRequest(GIS.Services.Testing.FolderService.GetDescriptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDescriptionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string format;
        
        public GetDescriptionRequestBody() {
        }
        
        public GetDescriptionRequestBody(string format) {
            this.format = format;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDescriptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDescriptionResponse", Namespace="http://tempuri.org/", Order=0)]
        public GIS.Services.Testing.FolderService.GetDescriptionResponseBody Body;
        
        public GetDescriptionResponse() {
        }
        
        public GetDescriptionResponse(GIS.Services.Testing.FolderService.GetDescriptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDescriptionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public string GetDescriptionResult;
        
        public GetDescriptionResponseBody() {
        }
        
        public GetDescriptionResponseBody(string GetDescriptionResult) {
            this.GetDescriptionResult = GetDescriptionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFolderServiceChannel : GIS.Services.Testing.FolderService.IFolderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FolderServiceClient : System.ServiceModel.ClientBase<GIS.Services.Testing.FolderService.IFolderService>, GIS.Services.Testing.FolderService.IFolderService {
        
        public FolderServiceClient() {
        }
        
        public FolderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FolderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FolderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FolderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GIS.Services.Testing.FolderService.GetDescriptionResponse GIS.Services.Testing.FolderService.IFolderService.GetDescription(GIS.Services.Testing.FolderService.GetDescriptionRequest request) {
            return base.Channel.GetDescription(request);
        }
        
        public string GetDescription(string format) {
            GIS.Services.Testing.FolderService.GetDescriptionRequest inValue = new GIS.Services.Testing.FolderService.GetDescriptionRequest();
            inValue.Body = new GIS.Services.Testing.FolderService.GetDescriptionRequestBody();
            inValue.Body.format = format;
            GIS.Services.Testing.FolderService.GetDescriptionResponse retVal = ((GIS.Services.Testing.FolderService.IFolderService)(this)).GetDescription(inValue);
            return retVal.Body.GetDescriptionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GIS.Services.Testing.FolderService.GetDescriptionResponse> GIS.Services.Testing.FolderService.IFolderService.GetDescriptionAsync(GIS.Services.Testing.FolderService.GetDescriptionRequest request) {
            return base.Channel.GetDescriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<GIS.Services.Testing.FolderService.GetDescriptionResponse> GetDescriptionAsync(string format) {
            GIS.Services.Testing.FolderService.GetDescriptionRequest inValue = new GIS.Services.Testing.FolderService.GetDescriptionRequest();
            inValue.Body = new GIS.Services.Testing.FolderService.GetDescriptionRequestBody();
            inValue.Body.format = format;
            return ((GIS.Services.Testing.FolderService.IFolderService)(this)).GetDescriptionAsync(inValue);
        }
    }
}
